displayName=Raven's Watch Plugin
author=Hayley
description=Official plugin for the Raven's Watch Clan.
tags=calendar, schedule, events, ravens watch
version=1.0.0
plugins=com.ravenswatch.RavensWatchPlugin
build=standard